name: Run main.py once
on: workflow_dispatch

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Update pip
        run: |
          python3 -m pip install --upgrade pip
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
      - name: Run main script
        env:
          BSKY_USER: ${{secrets.BSKY_USER}}
          BSKY_PASS: ${{secrets.BSKY_PASS}}
          CONSUMER_KEY: ${{secrets.CONSUMER_KEY}}
          CONSUMER_SECRET: ${{secrets.CONSUMER_SECRET}}
          TOKEN: ${{secrets.TOKEN}}
          TOKEN_SECRET: ${{secrets.TOKEN_SECRET}}
          BEARER_TOKEN: ${{secrets.BEARER_TOKEN}}

        run: |
          python3 main.py
